### ISSUE TITLE
Missing Output - Zoom

### ISSUE THREAD

**Issue by nicolasbvd** [kilianfroideva/heig-vd-dai-practical-content-1#4]
Missing of a class that copy the origin bitmap that create another bitmap that is zoomed.
Choosing the center and the scaling of the bitmap.

**Comment by kilianfroideva** [comment]
- Preserve original ratio => one option is a ratio (0->100%) that tells how much we zoom
- We can choose the point to zoom on => two options are ratio. The first one is how much in the width we need to move, the other is how much in the height we need to move from the top left corner.
- The resolution is changed.

**Comment by kilianfroideva** [comment]
Done
